### ISSUE TITLE
Deosn't work with django 1.11b

### ISSUE THREAD

**Issue by frankh** [nyaruka/django-hamlpy#60]
They seem to have removed templatize from trans_real in the new django beta, which breaks hamlpy

```
  File "/usr/local/lib/python3.6/site-packages/hamlpy/template/__init__.py", line 4, in <module>
    from . import templatize  # noqa
  File "/usr/local/lib/python3.6/site-packages/hamlpy/template/templatize.py", line 30, in <module>
    trans_real.templatize = decorate_templatize(trans_real.templatize)
AttributeError: module 'django.utils.translation.trans_real' has no attribute 'templatize'
```

**Comment by rowanseymour** [comment]
I think we can just patch it in `django.utils.translation.template` instead. If you're testing with Django 1.11b then feel free to try this and a PR will always be appreciated.

**Comment by rowanseymour** [comment]
Fixed in #62
